name: Build and push docker-image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to yandex-cr
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YCR_JSON_KEY }}

      - name: Build and push
        run: |
          docker build -t cr.yandex/crprumordku73faml62p/voohoo-tg:latest .
          docker push cr.yandex/crprumordku73faml62p/voohoo-tg:latest